### ISSUE TITLE
InvalidOperationException on WorldStatus

### ISSUE THREAD

**Issue by Purgator** [CK-Build/CKli#20]
Step to reproduce (probably some useless steps) :

CKli v0.3.1

- run \*pull\*
- run \*command\*
- git checkout master
- run \*command\*
- git pull
- \<Enter\>
```

>
> Trace: Executing World/DumpWorldState.
   > Info: World Status.
      - Error: Executing: World Status.
       ┌──────────────────────────■ Exception : InvalidOperationException ■──────────────────────────
       | Message: Collection was modified; enumeration operation may not execute.
       | Stack:    at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
       |           at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
       |           at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
       |           at System.Linq.Enumerable.DistinctIterator`1.FillSet()
       |           at System.Linq.Enumerable.DistinctIterator`1.ToList()
       |           at CK.Env.DriversCollection.WorldBranchContext..ctor(IEnumerable`1 drivers) in C:\CKli-World\CK-Core-Projects\CK-Core\CK.Env.World\DriversCollection.cs:line 42
       |           at CK.Env.DriversCollection.GetSolutionDependencyContextOnCurrentBranches(IActivityMonitor monitor, Boolean reloadSolutions) in C:\CKli-World\CK-Core-Projects\CK-Core\CK.Env.World\DriversCollection.cs:line 170
       |           at CKli.XWorld.OnDumpWorldStatus(IActivityMonitor m) in C:\CKli-World\CK-Core-Projects\CK-Core\CKli\XWorld.cs:line 103
       |           at CKli.XWorld.<.ctor>b__4_0(Object o, EventMonitoredArgs e) in C:\CKli-World\CK-Core-Projects\CK-Core\CKli\XWorld.cs:line 46
       |           at CK.Env.World.<>c__DisplayClass26_0.<DumpWorldState>b__0(IActivityMonitor m, Func`1 error) in C:\CKli-World\CK-Core-Projects\CK-Core\CK.Env.World\World.cs:line 152
       |           at CK.Env.World.RunSafe(IActivityMonitor m, String message, Action`2 action) in C:\CKli-World\CK-Core-Projects\CK-Core\CK.Env.World\World.cs:line 300
       └─────────────────────────────────────────────────────────────────────────────────────────────
   < Failed => WorkStatus = Idle, GlobalGitStatus = Unknown

```

**Comment by Purgator** [comment]
Typing \<Enter\> again solved the issue.

**Comment by Kuinox** [comment]
Writing a non regression test on it...

**Comment by Kuinox** [comment]
@Purgator The non regression test is red on v0.3.1 but is green on develop.
I released a new version, it should fix the bug.
